bot:
  name: kasyan_rpa6_telegram_bot
  token: 1309794458:AAHD1J0liCYQK7AklzwqrkD7PBy9Lbe7xIo
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-54-216-185-51.eu-west-1.compute.amazonaws.com:5432/dn0l5g7ikh9r6
    username: aeeazaxaowzkfz
    password: 99c492111b3f5c8720104f19a0f775152d13a36b5eb49573d15f5951ebaa4d67
    driverClassName: org.postgresql.Driver