bot:
  name: kasyan_rpa6_telegram_bot
  token: 1309794458:AAHD1J0liCYQK7AklzwqrkD7PBy9Lbe7xIo
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-99-80-200-225.eu-west-1.compute.amazonaws.com:5432/dcc6kvd6p8q22l
    username: rbaocowyamcfib
    password: 4a7eed570cacc0b0a455bf72b6179c91e3f165af89975ebb250bbe163955455b
    driverClassName: org.postgresql.Driver